### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by reiven** [Bystroushaak/bottle-rest#8]
Hi!
I'm very happy with bottle-rest.
Just FYI today i got this deprecation warning:

> local/lib/python2.7/site-packages/bottle_rest/bottle_rest.py:101: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

I'm using bottle-rest from pip v0.4.1

**Comment by Bystroushaak** [comment]
It should be fixed now.

**Comment by Bystroushaak** [comment]
I've released new version of the package.

**Comment by reiven** [comment]
Thanks @Bystroushaak
