### ISSUE TITLE
Py3 import issue

### ISSUE THREAD

**Issue by radek-senfeld** [Bystroushaak/bottle-rest#9]
Hi,
when using Py3 you now need to write `from bottle_rest.bottle_rest import json_to_data` to make it work properly. I fixed the problem by modifying `bottle_rest/__init__.py` to relative import.

`from bottle_rest import *` -> `from .bottle_rest import *`

Tested on Python 3.5.2

**Comment by Bystroushaak** [comment]
I've released new version 0.5.0, where this is fixed.
